version: '3.8'
services:
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - omegi-net

networks:
  omegi-net:
    external: true

volumes:
  mongodb_data:
    driver: local