version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    networks:
      - omegi-net
    environment:
      - RABBITMQ_DEFAULT_USER=omegi
      - RABBITMQ_DEFAULT_PASS=ssafy308@omegi
    restart: always

volumes:
  rabbitmq_data:

networks:
  omegi-net:
    external: true