services:
 kafdrop:
   image: obsidiandynamics/kafdrop:4.0.1
   container_name: kafdrop
   restart: "no"
   ports:
     - "19000:9000"
   environment:
     KAFKA_BROKERCONNECT: "kafka1:9092,kafka2:9092"
   depends_on:
     - "kafka1"
     - "kafka2"
   networks:
     - omegi-net

 zookeeper1:
   container_name: zookeeper1
   image: zookeeper:latest
   environment:
     ZOO_MY_ID: 1
     ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
   networks:
     - omegi-net

 zookeeper2:
   container_name: zookeeper2
   image: zookeeper:latest
   environment:
     ZOO_MY_ID: 2
     ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
   networks:
     - omegi-net

 zookeeper3:
   container_name: zookeeper3
   image: zookeeper:latest
   environment:
     ZOO_MY_ID: 3
     ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
   networks:
     - omegi-net

 kafka1:
   container_name: kafka1
   hostname: kafka1
   image: bitnami/kafka:latest
   depends_on:
     - zookeeper1
     - zookeeper2
     - zookeeper3
   ports:
     - "19092:19092"
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://k10a308.p.ssafy.io:19092
     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
     KAFKA_LOG_RETENTION_HOURS: 24
     KAFKA_MESSAGE_MAX_BYTES: 1048576 # 1MB
   networks:
     - omegi-net

 kafka2:
   container_name: kafka2
   image: bitnami/kafka:latest
   depends_on:
     - zookeeper1
     - zookeeper2
     - zookeeper3
   ports:
     - "29092:29092"
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://k10a308.p.ssafy.io:29092  
     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
     KAFKA_LOG_RETENTION_HOURS: 24
     KAFKA_MESSAGE_MAX_BYTES: 1048576
   networks:
     - omegi-net

networks:
 omegi-net:
   external: true
